### ISSUE TITLE
Fix mobile scrolling & style issues

### ISSUE THREAD

**Issue by samrose3** [samrose3/shrink-link#25]
## Todo

- [x] Add scroll `-webkit-overflow-scrolling: touch;`
- [x] Fix Details height
- [x] Fix spacing below History
