### ISSUE TITLE
Replace Carbon styles with new design and layout

### ISSUE THREAD

**Issue by samrose3** [samrose3/shrink-link#4]
## Description

The Carbon styles work, but let's form our own identity.

## Todo

*Can be made separate issues, but reference them here*

- [ ] Finalize first draft redesign
- [ ] Revise desktop layout
- [ ] Implement mobile layout
- [ ] Remove Carbon Components
- [ ] Remove Carbon styles

## Design Proposal

| Desktop | Mobile |
| ------- | ------ |
|![Desktop - Tabs](https://user-images.githubusercontent.com/11774595/54489390-b36cb780-4879-11e9-91dd-6ef95152fe78.jpg)|![Mobile - Scroll](https://user-images.githubusercontent.com/11774595/54489391-b7003e80-4879-11e9-9c29-edaf87a41de6.jpg)|
